DROP TABLE AspNetRoleClaims
DROP TABLE __EFMigrationsHistory
DROP TABLE AspNetUserClaims
DROP TABLE AspNetUserLogins
DROP TABLE AspNetUserRoles
DROP TABLE AspNetUsers
DROP TABLE AspNetUserTokens
DROP TABLE ChildProfiles
DROP TABLE UserProfileCategories
DROP TABLE UserProfiles
DROP TABLE Categories
DROP TABLE AspNetRoles
DROP TABLE ChatMessages
DROP TABLE Chats
DROP TABLE GroupMemberships
DROP TABLE Groups
DROP TABLE UnreadMessages
DROP TABLE UserChats
DROP TABLE UserContacts
DROP TABLE UserProfiles