services:
  azure-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: "azurite-blob --blobHost 0.0.0.0 --skipApiVersionCheck --inMemoryPersistence"
    ports:
      - "10000:10000"
  sqlserver:
    build:
      context: ./sqlserver
      dockerfile: ./Dockerfile
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
